### ISSUE TITLE
Can not download datasets

### ISSUE THREAD

**Issue by CreaterLL** [EnyanDai/RSGNN#1]
Hi,Could you pleace upload the .npz datasets used in the thesis? I can't down the dataset according to the code.
![image](https://user-images.githubusercontent.com/63894612/165009522-67fa3ba9-5891-43e2-9963-bebbcc5727f4.png)
and when i use the dataset downloaded from another link ,the following exception occured:
![image](https://user-images.githubusercontent.com/63894612/165009806-b8bb6bbf-ea2e-49cf-9679-e7a986369765.png)

**Comment by jinyilun718** [comment]
You can manually downloading data online, and put the downloaded data in the data dir.
