### ISSUE TITLE
Not end-to-end joint training as described in paper

### ISSUE THREAD

**Issue by veghen** [EnyanDai/RSGNN#2]
In the paper it's said the GCN and link predictor are jointly trained in an end-to-end manner. But in the code it seems that it's not end-to-end and it's more like the alternating optimization schema in https://github.com/ChandlerBang/Pro-GNN. May I know what's the difference between the two?

**Comment by EnyanDai** [comment]
Hi, thanks for your interests.
Your are right that we follow the alternating optimization in Pro-GNN. But this is still an end-to-end training as the gradients from the GCN classification loss will be propagated from GCN to the link predictor.  The reason of alternating training them is to balance the training pace of two modules.
